vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: asstes//images/posters
            upload_destination: '%kernel.project_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

